/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetectionsRouteImport } from './routes/detections'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SpeciesIndexRouteImport } from './routes/species.index'
import { Route as SpeciesSciNameRouteImport } from './routes/species.$sciName'
import { Route as ApiAudioDateSpeciesAndFileRouteImport } from './routes/api/audio/$date/$speciesAndFile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsRoute = DetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpeciesRoute,
} as any)
const SpeciesSciNameRoute = SpeciesSciNameRouteImport.update({
  id: '/$sciName',
  path: '/$sciName',
  getParentRoute: () => SpeciesRoute,
} as any)
const ApiAudioDateSpeciesAndFileRoute =
  ApiAudioDateSpeciesAndFileRouteImport.update({
    id: '/api/audio/$date/$speciesAndFile',
    path: '/api/audio/$date/$speciesAndFile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/learn': typeof LearnRoute
  '/species': typeof SpeciesRouteWithChildren
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/today': typeof TodayRoute
  '/species/$sciName': typeof SpeciesSciNameRoute
  '/species/': typeof SpeciesIndexRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/learn': typeof LearnRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/today': typeof TodayRoute
  '/species/$sciName': typeof SpeciesSciNameRoute
  '/species': typeof SpeciesIndexRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/learn': typeof LearnRoute
  '/species': typeof SpeciesRouteWithChildren
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/today': typeof TodayRoute
  '/species/$sciName': typeof SpeciesSciNameRoute
  '/species/': typeof SpeciesIndexRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/detections'
    | '/learn'
    | '/species'
    | '/stats'
    | '/timeline'
    | '/today'
    | '/species/$sciName'
    | '/species/'
    | '/api/audio/$date/$speciesAndFile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/detections'
    | '/learn'
    | '/stats'
    | '/timeline'
    | '/today'
    | '/species/$sciName'
    | '/species'
    | '/api/audio/$date/$speciesAndFile'
  id:
    | '__root__'
    | '/'
    | '/detections'
    | '/learn'
    | '/species'
    | '/stats'
    | '/timeline'
    | '/today'
    | '/species/$sciName'
    | '/species/'
    | '/api/audio/$date/$speciesAndFile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetectionsRoute: typeof DetectionsRoute
  LearnRoute: typeof LearnRoute
  SpeciesRoute: typeof SpeciesRouteWithChildren
  StatsRoute: typeof StatsRoute
  TimelineRoute: typeof TimelineRoute
  TodayRoute: typeof TodayRoute
  ApiAudioDateSpeciesAndFileRoute: typeof ApiAudioDateSpeciesAndFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections': {
      id: '/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof DetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/': {
      id: '/species/'
      path: '/'
      fullPath: '/species/'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof SpeciesRoute
    }
    '/species/$sciName': {
      id: '/species/$sciName'
      path: '/$sciName'
      fullPath: '/species/$sciName'
      preLoaderRoute: typeof SpeciesSciNameRouteImport
      parentRoute: typeof SpeciesRoute
    }
    '/api/audio/$date/$speciesAndFile': {
      id: '/api/audio/$date/$speciesAndFile'
      path: '/api/audio/$date/$speciesAndFile'
      fullPath: '/api/audio/$date/$speciesAndFile'
      preLoaderRoute: typeof ApiAudioDateSpeciesAndFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpeciesRouteChildren {
  SpeciesSciNameRoute: typeof SpeciesSciNameRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
}

const SpeciesRouteChildren: SpeciesRouteChildren = {
  SpeciesSciNameRoute: SpeciesSciNameRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
}

const SpeciesRouteWithChildren =
  SpeciesRoute._addFileChildren(SpeciesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetectionsRoute: DetectionsRoute,
  LearnRoute: LearnRoute,
  SpeciesRoute: SpeciesRouteWithChildren,
  StatsRoute: StatsRoute,
  TimelineRoute: TimelineRoute,
  TodayRoute: TodayRoute,
  ApiAudioDateSpeciesAndFileRoute: ApiAudioDateSpeciesAndFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
