/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetectionsRouteImport } from './routes/detections'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as ApiAudioDateSpeciesAndFileRouteImport } from './routes/api/audio/$date/$speciesAndFile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsRoute = DetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioDateSpeciesAndFileRoute =
  ApiAudioDateSpeciesAndFileRouteImport.update({
    id: '/api/audio/$date/$speciesAndFile',
    path: '/api/audio/$date/$speciesAndFile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/species': typeof SpeciesRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/species': typeof SpeciesRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/species': typeof SpeciesRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/detections' | '/species' | '/api/audio/$date/$speciesAndFile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detections' | '/species' | '/api/audio/$date/$speciesAndFile'
  id:
    | '__root__'
    | '/'
    | '/detections'
    | '/species'
    | '/api/audio/$date/$speciesAndFile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetectionsRoute: typeof DetectionsRoute
  SpeciesRoute: typeof SpeciesRoute
  ApiAudioDateSpeciesAndFileRoute: typeof ApiAudioDateSpeciesAndFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections': {
      id: '/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof DetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$date/$speciesAndFile': {
      id: '/api/audio/$date/$speciesAndFile'
      path: '/api/audio/$date/$speciesAndFile'
      fullPath: '/api/audio/$date/$speciesAndFile'
      preLoaderRoute: typeof ApiAudioDateSpeciesAndFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetectionsRoute: DetectionsRoute,
  SpeciesRoute: SpeciesRoute,
  ApiAudioDateSpeciesAndFileRoute: ApiAudioDateSpeciesAndFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
